-- 1. สร้างตารางหมวดหมู่อาหาร (Categories)
CREATE TABLE IF NOT EXISTS categories (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    display_order INTEGER DEFAULT 0
);

-- 2. สร้างตารางรายการอาหาร (Menu Items)
CREATE TABLE IF NOT EXISTS menu_items (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    image_url TEXT,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. สร้างตารางพนักงาน (Staff)
CREATE TABLE IF NOT EXISTS staff (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    pin_code TEXT NOT NULL, -- รหัส PIN เข้าใช้งาน เช่น "1234"
    role TEXT DEFAULT 'staff' -- 'staff' หรือ 'admin'
);

-- 4. สร้างตารางสั่งซื้อ (Orders)
CREATE TABLE IF NOT EXISTS orders (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number TEXT NOT NULL, -- เลขโต๊ะ หรือ 'Takeaway'
    status TEXT DEFAULT 'pending', -- 'pending' (รอรับออเดอร์), 'cooking' (กำลังทำ), 'served' (เสิร์ฟแล้ว), 'completed' (จ่ายเงินแล้ว), 'cancelled' (ยกเลิก)
    order_type TEXT DEFAULT 'dine-in', -- 'dine-in' หรือ 'takeaway'
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. สร้างตารางรายการอาหารในคำสั่งซื้อ (Order Items)
CREATE TABLE IF NOT EXISTS order_items (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id INTEGER REFERENCES menu_items(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    notes TEXT, -- โน้ต เช่น "ไม่เผ็ด", "ไข่ดาวไม่สุก"
    unit_price NUMERIC(10, 2) NOT NULL
);

-- 6. เพิ่มข้อมูลตัวอย่าง (Seed Data)

-- หมวดหมู่
INSERT INTO categories (name, display_order) VALUES
('อาหารจานเดี่ยว', 1),
('ของทานเล่น', 2),
('ของหวาน', 3),
('เครื่องดื่ม', 4)
ON CONFLICT (name) DO NOTHING;

-- ดึง ID ของหมวดหมู่มาใช้ใส่เมนูอาหาร
-- อาหารจานเดี่ยว (Main Dishes)
INSERT INTO menu_items (name, description, price, image_url, category_id) VALUES
('ข้าวกะเพราหมูสับไข่ดาว', 'ข้าวสวยร้อนๆ ราดกะเพราหมูสับรสชาติจัดจ้าน พร้อมไข่ดาวกรอบ', 75.00, 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500&auto=format&fit=crop&q=60', 1),
('ข้าวผัดปู', 'ข้าวผัดปูเมล็ดร่วนหอมกลิ่นกระทะ เนื้อปูเน้นๆ เสิร์ฟพร้อมมะนาวและแตงกวา', 90.00, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&auto=format&fit=crop&q=60', 1),
('ผัดไทยกุ้งสด', 'ผัดไทยเส้นเหนียวนุ่ม ผัดกับซอสมะขามสูตรพิเศษและกุ้งสดตัวโต', 85.00, 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500&auto=format&fit=crop&q=60', 1)
ON CONFLICT DO NOTHING;

-- ของทานเล่น (Appetizers)
INSERT INTO menu_items (name, description, price, image_url, category_id) VALUES
('ปีกไก่ทอดน้ำปลา', 'ปีกไก่หมักน้ำปลาสูตรเด็ด ทอดจนสีเหลืองกรอบนอกนุ่มใน', 119.00, 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=500&auto=format&fit=crop&q=60', 2),
('เฟรนช์ฟรายส์ซอสมะเขือเทศ', 'เฟรนช์ฟรายส์ชิ้นโตทอดร้อนๆ โรยเกลือเล็กน้อย เสิร์ฟพร้อมซอส', 69.00, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&auto=format&fit=crop&q=60', 2)
ON CONFLICT DO NOTHING;

-- ของหวาน (Desserts)
INSERT INTO menu_items (name, description, price, image_url, category_id) VALUES
('ข้าวเหนียวมะม่วง', 'ข้าวเหนียวมูนราดน้ำกะทิหอมหวาน ทานคู่กับมะม่วงน้ำดอกไม้สุก', 120.00, 'https://images.unsplash.com/photo-1528279027-68f0d7fce9f1?w=500&auto=format&fit=crop&q=60', 3),
('บิงซูชาไทย', 'เกล็ดหิมะรสชาไทยเข้มข้น ท็อปปิ้งด้วยเฉาก๊วยและนมข้นหวาน', 149.00, 'https://images.unsplash.com/photo-1518013041235-0133b2894867?w=500&auto=format&fit=crop&q=60', 3)
ON CONFLICT DO NOTHING;

-- เครื่องดื่ม (Drinks)
INSERT INTO menu_items (name, description, price, image_url, category_id) VALUES
('ชาไทยเย็น', 'ชาไทยชงสดสไตล์ดั้งเดิม หวานมันกลมกล่อม', 45.00, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60', 4),
('อเมริกาโน่เย็น', 'กาแฟอาราบิก้าแท้สกัดช็อตเข้มข้นผสมน้ำเย็น ดื่มแล้วสดชื่น', 55.00, 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop&q=60', 4),
('น้ำเก๊กฮวยเย็น', 'น้ำเก๊กฮวยต้มสมุนไพรจีน หวานน้อย ดับกระหาย', 35.00, 'https://images.unsplash.com/photo-1543257580-7269da773bf5?w=500&auto=format&fit=crop&q=60', 4)
ON CONFLICT DO NOTHING;

-- บัญชีพนักงานตัวอย่าง
INSERT INTO staff (username, pin_code, role) VALUES
('พนักงานกะเช้า', '1234', 'staff'),
('ผู้จัดการร้าน', '9999', 'admin')
ON CONFLICT (username) DO NOTHING;
